name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Fail
        if: ${{ failure() }}
        run: echo "Error" ; exit 1
      - name: Pass
        if: ${{ success() }}
        run: echo "Pass"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          key: ${{ secrets.ssh }}
          port: ${{ secrets.port }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/git/lapetitefe
            git stash
            git pull --force origin main
            npm run build
